name: 'Tests: node.js, promise-shimmed'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '0.10 || 0.12 || >= 1'
      type: majors
      command: npm run test:promise-shimmed

  node:
    name: 'node, promise-shimmed tests'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
